popopong/dont-die-food

app/controllers/pantry_items_controller.rb, app/controllers/recipes_controller.rb, app/views/pantry_items/index.html.erb, app/views/recipes/show.html.erb, config/routes.rb, test/controllers/pantry_items_controller_test.rb, test/controllers/recipes_controller_test.rb
- Created basic controllers (for pantry_items and recipes)
- Added a new route for routes#index
- Added views for controller methods I created
=> Created basic controllers and added index route for pantry items

db/seeds.rb
Seeded rice, coconut and lamb recipes in my master DB!
=> Seed more recipes

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/controllers/pantry_items_controller.rb, app/views/layouts/application.html.erb, app/views/pantry_items/index.html.erb, app/views/shared/_navbar_user.html copy.erb, app/views/shared/_navbar_user.html.erb, app/views/shared/_navbar_visitor.html.erb
=> Starting views

app/controllers/application_controller.rb, app/views/shared/_navbar_user.html.erb, app/views/shared/_navbar_visitor.html.erb
=> Added authentication for all actions

app/controllers/food_trades_controller.rb, app/controllers/saved_recipes_controller.rb, app/models/user.rb, app/views/pages/home.html.erb, app/views/pantry_items/index.html.erb, app/views/shared/_navbar_user.html.erb, app/views/shared/_navbar_visitor.html.erb, config/routes.rb
=> Fixed devise

app/controllers/pantry_items_controller.rb, app/controllers/users_controller.rb, app/views/users/show.html.erb, config/routes.rb, db/seeds.rb, test/controllers/users_controller_test.rb
- User show route + page
- User controller + methods
- Pantry items delete route + method in controller
=> Added some backend touches

app/javascript/components/typed_js.js, app/javascript/packs/application.js, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/pages/home.html.erb, package-lock.json, package.json, yarn.lock
After pulling,
please run `yarn install` `yarn add typed.js`
=> Added type.js on homepage & downloaded views from devise

db/seeds.rb
=> Fixed unexpected end

app/views/shared/_navbar_user.html.erb
Forgot to change branches!!! But fixed the navbar when user is signed in and when we click on avatar, goes to current_user's profile 😄
=> Fixed navbar link user avatar when user is signed in

app/views/saved_recipes/index.html.erb
I fixed the link to redirect to the right recipe.
Just forgot to specify saved_recipe_path(saved_recipe.**recipe**) in the link on the view page
=> Fixed the recipe link to redirect to the right recipe

app/views/pages/home.html.erb
On home page,
- Added a search field
- Added two submit buttons
- But the search form doesn't work yet, didn't code the actual search action
- Will need to add if statement to redirect to the right page (when user clicks on "Make a dish" or "Give away"
=> Added search field and submit buttons

app/assets/stylesheets/components/_button.scss, app/views/chatrooms/show.html.erb, app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/food_trades/index.html.erb, app/views/food_trades/new.html.erb, app/views/food_trades/show.html.erb, app/views/food_trades/user_food_trades.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/pantry_items/index.html.erb, app/views/saved_recipes/index.html.erb
Added containers to every page, but avoided containers where carosels needed to have the full page width
Fixed button behavior, color should not change on hover/click anymore
=> Button and container

app/assets/config/manifest.js, app/assets/stylesheets/components/_forms.scss, app/javascript/packs/application.js, app/javascript/plugins/init_select2.js, app/views/food_trades/new.html.erb, app/views/layouts/application.html.erb
please run `yarn install` and `bundle install`
=> styled food trade form

Gemfile, app/assets/stylesheets/components/_forms.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_message_cards.scss, app/controllers/food_trades_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/views/chatrooms/index.html.erb, app/views/chatrooms/show.html.erb, app/views/layouts/application.html.erb
- Fixed the map showing only 1/2 the time
- Fixed the map zooming in on montreal (and not washington)
- Need the bottom navbar js to work in order for the map to fully work
- Fixed the custom markers showing on top of default markers
=> Fixed the map issue

app/views/chatrooms/show.html.erb
=> worked on chatroom show page

app/assets/stylesheets/components/_map.scss, app/javascript/plugins/init_mapbox.js, app/views/shared/_btm_navbar.html.erb
- Added some styling to map on community page
- Tried fixing the map so it shows every time, centered on Montreal
- Added Poyan's code to fix the bottom navbar and we can work signed in
=> Food trades

app/assets/stylesheets/components/_forms.scss, app/javascript/packs/application.js, app/javascript/plugins/init_select2.js
Formatting and functionality done.
This functionality belong in the recipe.show page, not in search
Show how many ingredients the user has compared to the recipe
Include pantry items in show page and in search
=> Search Bar Done

app/assets/stylesheets/components/_index.scss, app/controllers/chatrooms_controller.rb, app/javascript/components/chatroom.js, app/views/messages/_sent_message.html.erb
- Fixed chatroom showing only 1 card per chat
=> Fixed the error

app/assets/config/manifest.js, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb
linked the css file to application.css
=> Fix bugs for heroku

app/assets/stylesheets/components/_card.scss, app/views/food_trades/fruits.html.erb
-fix uploaded image size in carousel home and index food trade page and category page
=> fix size of uplaoded images

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_list.scss, app/views/food_trades/fruits.html.erb
- fix checkbox with full circle in the recipe ingredients
=> Full circle checkbox

app/assets/stylesheets/components/_chat_cards.scss, app/views/chatrooms/index.html.erb, app/views/shared/_navbar_user.html.erb, db/schema.rb
- flip user name with ingredient name
- Capitalize user name and ingredient
- reduce size font ingredient
=> reset spacing chatrooms card

app/assets/stylesheets/components/_forms.scss, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
- Center "remember me"
- add some margin around button and links
=> Center remember me

app/controllers/application_controller.rb, app/controllers/food_trades_controller.rb, app/policies/ingredient_policy.rb, app/views/layouts/application.html.erb, test/policies/ingredient_policy_test.rb
=> fixed the dynamic form :D

app/views/pages/home.html.erb
- fix div in the home page to have padding for the content class
=> fix bottom padding home page

app/views/food_trades/_form.html.erb, app/views/food_trades/edit.html.erb
Styled form to edit food trade item
=> My item edit form

app/views/food_trades/index.html.erb
=> change text for trade food btn

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_my_giveaway_card.scss
- reset giveaway content to be the same as the cookbook card
=> Give awaycard
